//! Protocol-level named prepared statements.
//!
//! Without these, transaction mode is unusable for every mainstream driver:
//! pgjdbc prepares after five executions, psycopg3 after five, asyncpg prepares
//! everything, pgx defaults to `QueryExecModeCacheStatement`, and Npgsql
//! auto-prepares. Each of them names a statement once and expects the name to
//! keep working on whichever link it lands on next.
//!
//! The cache is **content-addressed**: two clients that prepare the same text
//! with the same parameter types share one server-side statement whatever they
//! chose to call it. The identity is the full [`StatementKey`] — query bytes and
//! parameter type OIDs — and never a digest of it. A 64-bit fingerprint used as
//! identity has a birthday collision at a few hundred million distinct
//! statements, and the consequence of that collision is not a cache miss: it is
//! running *a different client's query* under this client's parameters. Hash
//! values may therefore be used to find a bucket and never to decide equality,
//! which is what [`HashMap`] with a full-key comparator gives.
//!
//! That sharing is **bounded, and therefore best-effort**. The intern table holds a capacity's
//! worth of statements and evicts by least recent use, because its key owns the query text and
//! an unbounded table would retain every distinct statement the proxy has ever seen. Once an
//! entry is evicted, the next client to prepare the same text is given a *new* id and a new
//! name — so "same text implies same id" holds only while the entry is resident, and nothing
//! may depend on it for correctness. What it costs when it does not hold is a second `Parse`
//! on the backend, which each link's own LRU eventually closes.

use std::collections::hash_map::RandomState;
use std::collections::{HashMap, VecDeque};
use std::fmt;
use std::hash::BuildHasher;
use std::sync::Arc;

use bytes::Bytes;
use thiserror::Error;

/// The identity of a prepared statement.
///
/// Deliberately *not* the client-given name: two clients that pick different
/// names for the same query would then get two server-side statements, and one
/// client that reuses a name for a different query would silently get the wrong
/// one.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct StatementKey {
    query: Bytes,
    param_types: Arc<[u32]>,
}

impl StatementKey {
    pub fn new(query: Bytes, param_types: impl Into<Arc<[u32]>>) -> Self {
        Self {
            query,
            param_types: param_types.into(),
        }
    }

    pub fn query(&self) -> &Bytes {
        &self.query
    }

    pub fn param_types(&self) -> &[u32] {
        &self.param_types
    }
}

/// A server-side statement name generated by the pool.
///
/// `PostgreSQL` truncates identifiers at `NAMEDATALEN - 1` = 63 bytes, and a
/// truncated name is a name collision.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct StatementName(Bytes);

impl StatementName {
    pub const MAX_LEN: usize = 63;
    const PREFIX: &'static str = "pgel_";

    pub fn new(bytes: Bytes) -> Result<Self, StatementNameError> {
        if bytes.is_empty() || bytes.len() > Self::MAX_LEN {
            return Err(StatementNameError { len: bytes.len() });
        }
        Ok(Self(bytes))
    }

    fn generated(id: u64) -> Self {
        let name = format!("{}{id:016x}", Self::PREFIX);
        debug_assert!(name.len() <= Self::MAX_LEN);
        Self(Bytes::from(name))
    }

    pub fn as_bytes(&self) -> &Bytes {
        &self.0
    }

    /// Whether `name` has the exact shape this cache mints.
    ///
    /// Names are the prefix plus a fixed-width hex id, so they are trivially guessable. A
    /// client that names one it never prepared would otherwise reach whatever statement
    /// another client of the same pool key had put there.
    pub fn is_generated(name: &[u8]) -> bool {
        name.len() == Self::PREFIX.len() + 16
            && name.starts_with(Self::PREFIX.as_bytes())
            && name[Self::PREFIX.len()..].iter().all(u8::is_ascii_hexdigit)
    }

    /// Moves a client-chosen name out of the pool's namespace, keeping its length.
    ///
    /// Sent on to the backend rather than refused here, so the answer is `PostgreSQL`'s own
    /// `26000` and the outstanding queue keeps the error-recovery-to-`Sync` semantics the
    /// protocol defines. A minted name always has `_` at the prefix boundary, so replacing
    /// that one byte cannot land on another minted name.
    pub fn escaped(name: &Bytes) -> Bytes {
        let mut escaped = name.to_vec();
        escaped[Self::PREFIX.len() - 1] = b'x';
        Bytes::from(escaped)
    }
}

impl fmt::Display for StatementName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&String::from_utf8_lossy(&self.0))
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
#[error("prepared statement name of {len} bytes is outside 1..={max}", max = StatementName::MAX_LEN)]
pub struct StatementNameError {
    pub len: usize,
}

/// A statement in the global cache.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PreparedStatement {
    id: u64,
    name: StatementName,
    key: StatementKey,
}

impl PreparedStatement {
    pub fn id(&self) -> u64 {
        self.id
    }

    /// The name used on the backend, which is never the client's name.
    pub fn name(&self) -> &StatementName {
        &self.name
    }

    pub fn key(&self) -> &StatementKey {
        &self.key
    }
}

/// The default number of distinct statements one instance's intern table keeps.
///
/// This table is not the per-link cache and its capacity is not the same quantity: a link holds
/// what one backend has parsed, this holds what the proxy has *named*, shared by every client on
/// the instance. Its whole value is that two clients sending the same text get the same id, so
/// the link parses once — which means the capacity has to cover an application's working set of
/// distinct statements rather than one connection's.
///
/// 2048 because an application with more than two thousand genuinely distinct statement texts is
/// one whose SQL is being generated with literals inlined, and for that shape sharing was never
/// going to work anyway; past that point the table would be retaining text to no purpose. Well
/// above `max_server_statements` on purpose — a table smaller than a link's own cache would
/// evict entries the link is still holding, and re-mint them on the next Bind.
pub const DEFAULT_GLOBAL_STATEMENTS: usize = 2048;

/// The process-wide content-addressed statement cache.
///
/// Bounded, and the bound is load-bearing rather than defensive. [`StatementKey`] owns the query
/// text, so an unbounded table retains every distinct statement the proxy has ever seen for the
/// lifetime of the process — which is unbounded in the query variety of the applications behind
/// it, not in anything an operator configured.
///
/// Eviction is safe because an entry's removal does not disturb the [`Arc`] a client or a link
/// still holds: the statement keeps its id, its minted name and its text, and only the *sharing*
/// is lost. A later intern of the same text mints a fresh id, so the backend ends up holding
/// that text twice until each link's own LRU closes the older one. Wasteful, and correct.
///
/// Generic over the hasher only so that the collision behaviour can be tested
/// directly; production use takes the default.
#[derive(Debug)]
pub struct GlobalStatementCache<S = RandomState> {
    entries: HashMap<StatementKey, Arc<PreparedStatement>, S>,
    /// Least recent first, in the same shape [`ServerStatements`] uses. A second eviction policy
    /// in this file with different mechanics would be a maintenance trap.
    recency: VecDeque<StatementKey>,
    capacity: usize,
    next_id: u64,
    evicted: u64,
}

impl Default for GlobalStatementCache {
    fn default() -> Self {
        Self::new()
    }
}

impl GlobalStatementCache {
    pub fn new() -> Self {
        Self::with_capacity(DEFAULT_GLOBAL_STATEMENTS)
    }

    pub fn with_capacity(capacity: usize) -> Self {
        Self {
            entries: HashMap::new(),
            recency: VecDeque::new(),
            capacity: capacity.max(1),
            next_id: 0,
            evicted: 0,
        }
    }
}

impl<S: BuildHasher> GlobalStatementCache<S> {
    pub fn with_hasher(hasher: S) -> Self {
        Self {
            entries: HashMap::with_hasher(hasher),
            recency: VecDeque::new(),
            capacity: DEFAULT_GLOBAL_STATEMENTS,
            next_id: 0,
            evicted: 0,
        }
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    pub fn capacity(&self) -> usize {
        self.capacity
    }

    /// How many entries the bound has discarded, so an operator can tell a table that is merely
    /// full from one that is thrashing.
    pub fn evicted(&self) -> u64 {
        self.evicted
    }

    /// Returns the shared statement for `key`, creating it if new.
    pub fn intern(&mut self, key: StatementKey) -> Arc<PreparedStatement> {
        if let Some(existing) = self.entries.get(&key) {
            let shared = Arc::clone(existing);
            self.touch(&key);
            return shared;
        }

        if self.entries.len() >= self.capacity {
            self.evict_oldest();
        }

        let id = self.next_id;
        self.next_id += 1;
        let statement = Arc::new(PreparedStatement {
            id,
            name: StatementName::generated(id),
            key: key.clone(),
        });
        self.entries.insert(key.clone(), Arc::clone(&statement));
        self.recency.push_back(key);
        statement
    }

    pub fn get(&self, key: &StatementKey) -> Option<&Arc<PreparedStatement>> {
        self.entries.get(key)
    }

    fn touch(&mut self, key: &StatementKey) {
        if let Some(position) = self.recency.iter().position(|candidate| candidate == key) {
            self.recency.remove(position);
        }
        self.recency.push_back(key.clone());
    }

    fn evict_oldest(&mut self) {
        if let Some(victim) = self.recency.pop_front() {
            self.entries.remove(&victim);
            self.evicted += 1;
        }
    }
}

/// One client's mapping from the names it chose to shared statements.
#[derive(Debug, Default)]
pub struct ClientStatements {
    by_name: HashMap<Bytes, Arc<PreparedStatement>>,
}

impl ClientStatements {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn len(&self) -> usize {
        self.by_name.len()
    }

    pub fn is_empty(&self) -> bool {
        self.by_name.is_empty()
    }

    /// Binds a client-chosen name to a shared statement.
    ///
    /// The unnamed statement is not cacheable: `PostgreSQL` replaces it on every
    /// `Parse` and destroys it at the end of the transaction, so a client using
    /// it is entitled to have its own, and sharing it across clients would let
    /// one client's `Bind` see another's text.
    pub fn insert(&mut self, name: Bytes, statement: Arc<PreparedStatement>) -> bool {
        if name.is_empty() {
            return false;
        }
        self.by_name.insert(name, statement);
        true
    }

    pub fn resolve(&self, name: &[u8]) -> Option<&Arc<PreparedStatement>> {
        self.by_name.get(name)
    }

    /// Forgets a name the client closed. The shared statement survives for the
    /// other clients that reference it.
    pub fn remove(&mut self, name: &[u8]) -> Option<Arc<PreparedStatement>> {
        self.by_name.remove(name)
    }

    pub fn clear(&mut self) {
        self.by_name.clear();
    }

    /// Re-interns every name against another cache, keeping the client's names.
    ///
    /// A session that follows its tenant to another instance changes which
    /// statement cache its ids and generated names come from, and those ids are
    /// per cache: carrying the old entries over would let a link on the new
    /// instance answer a `Bind` with whatever it happened to have parsed under
    /// the same id. Dropping them instead is no better - the client's own cache
    /// still holds the names, so its next `Bind` names a statement this session
    /// no longer knows and `PostgreSQL` refuses it with 26000. Only the text is
    /// portable, so the text is what is carried across and re-interned.
    pub fn rebind(&mut self, mut intern: impl FnMut(&StatementKey) -> Arc<PreparedStatement>) {
        for statement in self.by_name.values_mut() {
            *statement = intern(statement.key());
        }
    }
}

/// What must happen before a statement can be bound on a given link.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ServerAction {
    /// Already parsed on this link.
    Ready,
    /// Send `Parse` under this name; swallow the `ParseComplete`.
    Parse(StatementName),
    /// Evict first: send `Close` for `evict` — swallowing its `CloseComplete` —
    /// then `Parse` under `name`.
    EvictThenParse {
        evict: StatementName,
        name: StatementName,
    },
}

/// The statements currently parsed on one backend link, as an LRU.
#[derive(Debug)]
pub struct ServerStatements {
    capacity: usize,
    names: HashMap<u64, StatementName>,
    recency: VecDeque<u64>,
}

impl ServerStatements {
    pub fn new(capacity: usize) -> Self {
        Self {
            capacity: capacity.max(1),
            names: HashMap::new(),
            recency: VecDeque::new(),
        }
    }

    pub fn capacity(&self) -> usize {
        self.capacity
    }

    pub fn len(&self) -> usize {
        self.names.len()
    }

    pub fn is_empty(&self) -> bool {
        self.names.is_empty()
    }

    pub fn contains(&self, statement: &PreparedStatement) -> bool {
        self.names.contains_key(&statement.id)
    }

    /// Decides what to send before binding `statement` on this link, and
    /// records the outcome as if it had been sent.
    pub fn ensure(&mut self, statement: &PreparedStatement) -> ServerAction {
        if self.names.contains_key(&statement.id) {
            self.touch(statement.id);
            return ServerAction::Ready;
        }

        let evicted = if self.names.len() >= self.capacity {
            self.evict_oldest()
        } else {
            None
        };

        self.names.insert(statement.id, statement.name.clone());
        self.recency.push_back(statement.id);

        match evicted {
            Some(evict) => ServerAction::EvictThenParse {
                evict,
                name: statement.name.clone(),
            },
            None => ServerAction::Parse(statement.name.clone()),
        }
    }

    /// Forgets everything, because the backend has.
    ///
    /// Called when a `DEALLOCATE ALL` or `DISCARD ALL` passes through, and
    /// whenever the link is scrubbed.
    pub fn clear(&mut self) {
        self.names.clear();
        self.recency.clear();
    }

    fn touch(&mut self, id: u64) {
        if let Some(position) = self.recency.iter().position(|candidate| *candidate == id) {
            self.recency.remove(position);
        }
        self.recency.push_back(id);
    }

    fn evict_oldest(&mut self) -> Option<StatementName> {
        let victim = self.recency.pop_front()?;
        self.names.remove(&victim)
    }
}

/// A statement passing through that invalidates what the pool believes is
/// parsed on the link.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CacheInvalidation {
    /// `DEALLOCATE ...` — every prepared statement may be gone.
    Deallocate,
    /// `DISCARD ...` — likewise, plus more.
    Discard,
}

/// Detects statements that drop the backend's prepared statements.
///
/// Only the *server-side* view is invalidated by this, never the client's name
/// map. That asymmetry is deliberate: the matcher is a token scan, not a parser,
/// so it can fire on text that is not really a `DISCARD` — and a spurious server
/// invalidation costs one re-`Parse`, whereas spuriously forgetting a client's
/// name would answer its next `Bind` with `26000 invalid_sql_statement_name`.
/// Missing a real one is what produces the ghost entries and the 26000 the other
/// way round, so the scan is deliberately over-eager.
pub fn detect_cache_invalidation(sql: &[u8]) -> Option<CacheInvalidation> {
    let mut found = None;
    for token in sql.split(|byte| !byte.is_ascii_alphanumeric() && *byte != b'_') {
        if token.eq_ignore_ascii_case(b"deallocate") {
            found = Some(CacheInvalidation::Deallocate);
        } else if token.eq_ignore_ascii_case(b"discard") {
            return Some(CacheInvalidation::Discard);
        }
    }
    found
}

#[cfg(test)]
mod tests {

    fn key_for(query: &str) -> StatementKey {
        StatementKey::new(Bytes::copy_from_slice(query.as_bytes()), Vec::new())
    }

    /// The intern table is bounded by configuration, not by how much SQL an application
    /// happens to contain.
    ///
    /// Its key holds the query text, so an unbounded table retains every distinct statement the
    /// proxy has ever seen for the life of the process. That is ordinary for any client that
    /// inlines literals instead of binding parameters, and it is invisible to both benchmarks:
    /// the density workload issues no queries and the throughput workload issues one.
    #[test]
    fn the_intern_table_stops_growing_at_its_capacity() {
        let mut cache = GlobalStatementCache::with_capacity(16);

        for n in 0..1_000 {
            cache.intern(key_for(&format!("SELECT {n}")));
        }

        assert_eq!(
            cache.len(),
            16,
            "a thousand distinct query texts must not become a thousand retained entries"
        );
    }

    /// Eviction is by least recent use, so a statement an application keeps asking for is not
    /// thrown away to make room for one it asked for once.
    #[test]
    fn the_statement_still_in_use_survives_the_ones_that_are_not() {
        let mut cache = GlobalStatementCache::with_capacity(4);
        let hot = cache.intern(key_for("SELECT hot"));

        for n in 0..100 {
            cache.intern(key_for(&format!("SELECT cold {n}")));
            // Asked for again on every round, so it is never the least recent.
            assert_eq!(
                cache.intern(key_for("SELECT hot")).id(),
                hot.id(),
                "the statement in continuous use was evicted at round {n}"
            );
        }
    }

    /// An evicted entry does not invalidate the `Arc` a live client still holds.
    ///
    /// This is what makes eviction safe at all. The client keeps its statement and the link
    /// keeps whatever it parsed under that id; a later intern of the same text simply mints a
    /// fresh id, so the backend ends up holding the text twice. Wasteful, and correct -- which
    /// is the trade the bound buys.
    #[test]
    fn evicting_an_entry_leaves_the_statement_a_client_still_holds_intact() {
        let mut cache = GlobalStatementCache::with_capacity(2);
        let held = cache.intern(key_for("SELECT held"));
        let (id, name) = (held.id(), held.name().clone());

        for n in 0..50 {
            cache.intern(key_for(&format!("SELECT other {n}")));
        }

        assert_eq!(
            held.id(),
            id,
            "a live statement changed identity underneath its holder"
        );
        assert_eq!(held.name(), &name, "a live statement's minted name changed");
        assert_eq!(
            held.key(),
            &key_for("SELECT held"),
            "a live statement's text changed"
        );

        // Re-interning the evicted text mints a new identity rather than resurrecting the old
        // one, which is exactly why the old Arc has to keep working.
        let again = cache.intern(key_for("SELECT held"));
        assert_ne!(
            again.id(),
            id,
            "an evicted entry was expected to be re-minted, not recovered"
        );
    }

    /// A capacity of zero is a configuration mistake, not an instruction to cache nothing and
    /// re-mint on every single Parse.
    #[test]
    fn a_capacity_of_zero_is_treated_as_one() {
        let mut cache = GlobalStatementCache::with_capacity(0);
        let first = cache.intern(key_for("SELECT 1"));

        assert_eq!(cache.intern(key_for("SELECT 1")).id(), first.id());
        assert_eq!(cache.len(), 1);
    }

    #[test]
    fn a_minted_name_is_recognised_and_a_client_name_is_not() {
        assert!(StatementName::is_generated(b"pgel_0000000000000000"));
        assert!(StatementName::is_generated(b"pgel_00000000deadbeef"));
        // A client is entitled to a name that merely starts the same way.
        assert!(!StatementName::is_generated(b"pgel_orders"));
        assert!(!StatementName::is_generated(b"pgel_000000000000000"));
        assert!(!StatementName::is_generated(b"pgel_0000000000000000x"));
        assert!(!StatementName::is_generated(b"pgel_00000000zzzzzzzz"));
        assert!(!StatementName::is_generated(b""));
    }

    #[test]
    fn escaping_a_name_keeps_its_length_and_leaves_the_minted_space() {
        let name = Bytes::from_static(b"pgel_0000000000000003");
        let escaped = StatementName::escaped(&name);

        assert_eq!(
            escaped.len(),
            name.len(),
            "the backend sees a name, not a truncation"
        );
        assert!(
            !StatementName::is_generated(&escaped),
            "an escaped name must not be able to land on another client's statement"
        );
        assert_ne!(escaped, name);
    }

    use std::hash::Hasher;

    use super::*;

    fn key(query: &str, param_types: &[u32]) -> StatementKey {
        StatementKey::new(
            Bytes::copy_from_slice(query.as_bytes()),
            param_types.to_vec(),
        )
    }

    #[test]
    fn the_same_text_and_types_share_one_server_side_statement() {
        let mut cache = GlobalStatementCache::new();
        let first = cache.intern(key("SELECT $1::int", &[23]));
        let second = cache.intern(key("SELECT $1::int", &[23]));
        assert_eq!(first.id(), second.id());
        assert_eq!(cache.len(), 1);
    }

    /// A session that follows its tenant to another instance keeps every name
    /// its driver still holds, and every name now points at the other cache's
    /// statement for the same text. Either half missing is a `Bind` the target
    /// refuses with 26000 while the client believes it was merely paused.
    #[test]
    fn following_a_tenant_to_another_instance_keeps_the_clients_names_resolvable() {
        let mut source = GlobalStatementCache::new();
        let mut target = GlobalStatementCache::new();
        // The target has already parsed something else, so its ids are not the
        // source's ids: carrying the old entry over would resolve to that.
        let decoy = target.intern(key("SELECT 'somebody else'", &[]));

        let mut client = ClientStatements::new();
        let name = Bytes::from_static(b"stmtcache_1");
        client.insert(name.clone(), source.intern(key("SELECT $1::int", &[23])));
        assert_eq!(client.resolve(&name).map(|s| s.id()), Some(decoy.id()));

        client.rebind(|key| target.intern(key.clone()));

        let rebound = client
            .resolve(&name)
            .expect("the client's name still resolves");
        assert_ne!(
            rebound.id(),
            decoy.id(),
            "the name resolved to another client's statement"
        );
        assert_eq!(rebound.key(), &key("SELECT $1::int", &[23]));
        assert_eq!(
            rebound.id(),
            target.intern(key("SELECT $1::int", &[23])).id()
        );
    }

    #[test]
    fn different_parameter_types_are_different_statements() {
        let mut cache = GlobalStatementCache::new();
        let int = cache.intern(key("SELECT $1", &[23]));
        let text = cache.intern(key("SELECT $1", &[25]));
        assert_ne!(int.id(), text.id());
        assert_eq!(cache.len(), 2);
    }

    #[test]
    fn a_missing_parameter_type_is_not_the_same_as_an_unspecified_one() {
        let mut cache = GlobalStatementCache::new();
        let unspecified = cache.intern(key("SELECT $1", &[]));
        let inferred = cache.intern(key("SELECT $1", &[0]));
        assert_ne!(unspecified.id(), inferred.id());
    }

    #[test]
    fn generated_names_fit_in_an_identifier() {
        for id in [0u64, 1, u64::MAX] {
            let name = StatementName::generated(id);
            assert!(name.as_bytes().len() <= StatementName::MAX_LEN);
        }
    }

    #[test]
    fn an_oversized_name_is_rejected() {
        let too_long = Bytes::from(vec![b'a'; StatementName::MAX_LEN + 1]);
        assert!(StatementName::new(too_long).is_err());
        assert!(StatementName::new(Bytes::new()).is_err());
        assert!(StatementName::new(Bytes::from_static(b"ok")).is_ok());
    }

    #[test]
    fn a_client_name_never_becomes_the_server_name() {
        let mut cache = GlobalStatementCache::new();
        let statement = cache.intern(key("SELECT 1", &[]));
        let mut client = ClientStatements::new();
        client.insert(Bytes::from_static(b"S_1"), Arc::clone(&statement));

        assert_ne!(statement.name().as_bytes(), &Bytes::from_static(b"S_1"));
        assert_eq!(client.resolve(b"S_1").unwrap().id(), statement.id());
    }

    #[test]
    fn two_clients_naming_the_same_query_differently_still_share_it() {
        let mut cache = GlobalStatementCache::new();
        let mut alice = ClientStatements::new();
        let mut bob = ClientStatements::new();

        let shared = key("SELECT $1::int", &[23]);
        alice.insert(Bytes::from_static(b"stmt_a"), cache.intern(shared.clone()));
        bob.insert(Bytes::from_static(b"pgjdbc_1"), cache.intern(shared));

        assert_eq!(cache.len(), 1);
        assert_eq!(
            alice.resolve(b"stmt_a").unwrap().name(),
            bob.resolve(b"pgjdbc_1").unwrap().name()
        );
    }

    #[test]
    fn the_unnamed_statement_is_never_cached() {
        let mut cache = GlobalStatementCache::new();
        let mut client = ClientStatements::new();
        assert!(!client.insert(Bytes::new(), cache.intern(key("SELECT 1", &[]))));
        assert!(client.is_empty());
    }

    #[test]
    fn closing_a_client_name_leaves_the_shared_statement_alone() {
        let mut cache = GlobalStatementCache::new();
        let statement = cache.intern(key("SELECT 1", &[]));
        let mut client = ClientStatements::new();
        client.insert(Bytes::from_static(b"s"), statement);

        assert!(client.remove(b"s").is_some());
        assert!(client.resolve(b"s").is_none());
        assert_eq!(cache.len(), 1);
    }

    #[test]
    fn a_statement_is_parsed_once_per_link() {
        let mut cache = GlobalStatementCache::new();
        let statement = cache.intern(key("SELECT 1", &[]));
        let mut server = ServerStatements::new(4);

        assert_eq!(
            server.ensure(&statement),
            ServerAction::Parse(statement.name().clone())
        );
        assert_eq!(server.ensure(&statement), ServerAction::Ready);
    }

    #[test]
    fn the_least_recently_used_statement_is_evicted() {
        let mut cache = GlobalStatementCache::new();
        let mut server = ServerStatements::new(2);

        let first = cache.intern(key("SELECT 1", &[]));
        let second = cache.intern(key("SELECT 2", &[]));
        let third = cache.intern(key("SELECT 3", &[]));

        server.ensure(&first);
        server.ensure(&second);
        server.ensure(&first);

        assert_eq!(
            server.ensure(&third),
            ServerAction::EvictThenParse {
                evict: second.name().clone(),
                name: third.name().clone(),
            }
        );
        assert!(server.contains(&first));
        assert!(!server.contains(&second));
        assert_eq!(server.len(), 2);
    }

    #[test]
    fn clearing_a_link_forces_every_statement_to_be_parsed_again() {
        let mut cache = GlobalStatementCache::new();
        let statement = cache.intern(key("SELECT 1", &[]));
        let mut server = ServerStatements::new(4);

        server.ensure(&statement);
        server.clear();
        assert_eq!(
            server.ensure(&statement),
            ServerAction::Parse(statement.name().clone())
        );
    }

    #[test]
    fn deallocate_and_discard_are_detected() {
        assert_eq!(
            detect_cache_invalidation(b"DEALLOCATE ALL"),
            Some(CacheInvalidation::Deallocate)
        );
        assert_eq!(
            detect_cache_invalidation(b"deallocate prepare all;"),
            Some(CacheInvalidation::Deallocate)
        );
        assert_eq!(
            detect_cache_invalidation(b"  DISCARD ALL  "),
            Some(CacheInvalidation::Discard)
        );
        assert_eq!(
            detect_cache_invalidation(b"SELECT 1; DISCARD ALL"),
            Some(CacheInvalidation::Discard)
        );
        assert_eq!(detect_cache_invalidation(b"SELECT 1"), None);
        assert_eq!(detect_cache_invalidation(b"SELECT discarded_at"), None);
    }

    /// Forces every key into one bucket, so nothing but the comparator can tell
    /// two statements apart.
    #[derive(Debug, Clone, Default)]
    struct CollidingHasher;

    impl Hasher for CollidingHasher {
        fn finish(&self) -> u64 {
            0
        }
        fn write(&mut self, _bytes: &[u8]) {}
    }

    impl BuildHasher for CollidingHasher {
        type Hasher = Self;
        fn build_hasher(&self) -> Self {
            Self
        }
    }

    #[test]
    fn statements_with_colliding_hashes_are_still_distinct() {
        let mut cache = GlobalStatementCache::with_hasher(CollidingHasher);

        let transfer = cache.intern(key("UPDATE accounts SET balance = $1", &[20]));
        let audit = cache.intern(key("DELETE FROM audit_log WHERE id = $1", &[20]));
        let same_text_other_types = cache.intern(key("UPDATE accounts SET balance = $1", &[701]));

        assert_eq!(cache.len(), 3);
        assert_ne!(transfer.id(), audit.id());
        assert_ne!(transfer.id(), same_text_other_types.id());
        assert_ne!(transfer.name(), audit.name());

        assert_eq!(
            cache
                .get(&key("DELETE FROM audit_log WHERE id = $1", &[20]))
                .unwrap()
                .id(),
            audit.id()
        );
        assert_eq!(
            cache
                .get(&key("UPDATE accounts SET balance = $1", &[20]))
                .unwrap()
                .key()
                .query(),
            &Bytes::from_static(b"UPDATE accounts SET balance = $1")
        );
    }
}
