/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package pgbackrest turns the operator's repository decisions into pgBackRest
// configuration and command lines.
//
// Everything in this file is a pure function returning a config body or an argv, so the
// exact bytes handed to pgBackRest are assertable without a repository, a PostgreSQL or a
// network. That matters more here than it would elsewhere: a wrong flag in an archive or a
// restore command is a silent data-loss bug discovered at restore time, which is the one
// moment there is nothing left to fall back on.
package pgbackrest

import (
	"fmt"
	"net/url"
	"strconv"
	"strings"
)

// Binary is the pgBackRest executable. It is resolved from PATH rather than from the
// PostgreSQL bin directory: it arrives from the distribution's package, not from the
// PostgreSQL build, and the two live in different places.
const Binary = "pgbackrest"

// stanzaPrefix makes a stanza recognisably ours in a bucket that may hold other things.
const stanzaPrefix = "pgelastic-"

// Repository locates the object store and bounds what is kept in it.
//
// It travels to the agent inside the mounted AgentConfig rather than being read from the
// PgInstance, because archive_command runs once per segment and must not need an API server
// to archive WAL. A repository that could only be discovered by asking Kubernetes would
// stop archiving during exactly the partitions that make an archive worth having.
type Repository struct {
	// Path is the destination URL, s3://bucket/prefix.
	Path string `json:"path"`
	// EndpointURL overrides the provider's default endpoint for S3-compatible stores.
	EndpointURL string `json:"endpointURL,omitempty"`
	// Region is the bucket's region.
	Region string `json:"region,omitempty"`
	// RetentionFull and RetentionWAL are the operator's durations, "30d" style.
	RetentionFull string `json:"retentionFull,omitempty"`
	RetentionWAL  string `json:"retentionWAL,omitempty"`
}

// Configured reports whether a repository was named at all. Until one is, WAL archiving is
// a no-op that reports success, because archive_mode is PGC_POSTMASTER and cannot be turned
// off without a restart that drops every tenant connection on the instance.
func (r Repository) Configured() bool { return strings.TrimSpace(r.Path) != "" }

// Credentials are the object store's key pair and, for a store presenting a certificate
// this cluster does not otherwise trust, the CA that signed it.
type Credentials struct {
	AccessKeyID     string
	SecretAccessKey string
	CABundlePath    string
}

// Layout are the in-pod paths pgBackRest acts on.
type Layout struct {
	// DataDir is PGDATA.
	DataDir string
	// SocketDir and Port address the local postmaster. pgBackRest connects over the Unix
	// socket as the bootstrap superuser, which is the only route to it: that role has no
	// password at all.
	SocketDir string
	Port      int32
	// SpoolPath backs asynchronous archiving. It lives on the WAL volume rather than the
	// data volume because it holds WAL-sized files and its worst case is bounded by the
	// same thing pg_wal's is.
	SpoolPath string
	// LogPath is where pgBackRest writes its own logs.
	LogPath string
}

// StanzaName names the repository stanza after the PostgreSQL system identifier.
//
// Not after the instance name. An instance deleted and recreated under a reused name would
// otherwise interleave its WAL into its predecessor's archive, and the two histories
// diverge at the instant of the recreate, so neither is restorable afterwards. The system
// identifier is generated by initdb and is the only identifier unique to a data directory's
// history.
//
// Note what this does *not* separate: a restored instance copies its source's control file
// verbatim, so it inherits the same system identifier and therefore the same stanza, while
// running on a forked timeline. Keeping a recovery instance out of its source's archive is
// a separate problem with a separate answer.
func StanzaName(systemIdentifier string) string {
	return stanzaPrefix + sanitiseStanza(systemIdentifier)
}

// sanitiseStanza keeps a stanza name inside the alphanumeric-dash-underscore set pgBackRest
// accepts. A system identifier is decimal digits, so this normally changes nothing; it
// exists so a malformed control file produces a rejected name rather than a command line
// with a path separator in it.
func sanitiseStanza(value string) string {
	return strings.Map(func(r rune) rune {
		switch {
		case r >= '0' && r <= '9', r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r == '-', r == '_':
			return r
		default:
			return '_'
		}
	}, value)
}

// Render returns the body of pgbackrest.conf.
//
// The credentials are written into the file rather than passed as flags or environment
// variables. Flags are visible in /proc to anything that can read the process table, and
// environment variables cannot be rotated without restarting the process that holds them;
// a file written 0600 beside override.conf, which already carries the replication password,
// is rotated by rewriting it.
func Render(
	repository Repository,
	credentials Credentials,
	layout Layout,
	stanza string,
) (string, error) {
	bucket, prefix, err := parsePath(repository.Path)
	if err != nil {
		return "", err
	}
	retention, err := retentionDays(repository)
	if err != nil {
		return "", err
	}

	global := []setting{
		{"repo1-type", "s3"},
		{"repo1-path", prefix},
		{"repo1-s3-bucket", bucket},
		{"repo1-s3-region", regionOrDefault(repository.Region)},
	}
	global = append(global, endpointSettings(repository.EndpointURL)...)
	if credentials.CABundlePath != "" {
		global = append(global, setting{"repo1-storage-ca-file", credentials.CABundlePath})
	}
	global = append(global,
		setting{"repo1-s3-key", credentials.AccessKeyID},
		setting{"repo1-s3-key-secret", credentials.SecretAccessKey},

		// Time-based expiry rather than a backup count, because the operator's contract is
		// a recovery window and a count only accidentally describes one. pgBackRest retains
		// archive for exactly the backups it retains, which is the invariant the API
		// promises: WAL retention always covers the oldest restorable full backup. WAL kept
		// beyond that would have no base backup to be replayed onto and is therefore not
		// retained, whatever a longer WAL retention asked for.
		setting{"repo1-retention-full-type", "time"},
		setting{"repo1-retention-full", strconv.Itoa(retention)},

		setting{"compress-type", "zst"},
		setting{"compress-level", "3"},

		// Asynchronous archiving. pgelastic packs many tenants onto one instance, so WAL is
		// produced faster than a synchronous archive_command can push it: archive_command
		// runs one segment at a time and blocks the archiver between segments. This is not
		// a tuning knob, it is the difference between keeping up and falling behind.
		setting{"archive-async", "y"},
		setting{"spool-path", layout.SpoolPath},
		setting{"process-max", "2"},

		// archive-push-queue-max is deliberately not set. It makes archive_command report
		// success and drop the segment once the queue is over the limit, trading a full
		// pg_wal for a hole in the archive. A full pg_wal is an outage; a hole in the
		// archive is an unrestorable instance nobody finds out about until they try.

		setting{"log-path", layout.LogPath},
		setting{"log-level-console", "info"},
		setting{"log-level-file", "off"},
	)

	body := &strings.Builder{}
	body.WriteString("# Generated by pgelastic. Edits are overwritten on the next render.\n")
	writeSection(body, "global", global)
	writeSection(body, stanza, []setting{
		{"pg1-path", layout.DataDir},
		{"pg1-socket-path", layout.SocketDir},
		{"pg1-port", strconv.Itoa(int(layout.Port))},
	})
	return body.String(), nil
}

type setting struct{ name, value string }

func writeSection(body *strings.Builder, name string, settings []setting) {
	fmt.Fprintf(body, "\n[%s]\n", name)
	for _, item := range settings {
		fmt.Fprintf(body, "%s=%s\n", item.name, item.value)
	}
}

// parsePath splits s3://bucket/prefix into its two halves.
func parsePath(raw string) (bucket, prefix string, err error) {
	parsed, err := url.Parse(strings.TrimSpace(raw))
	if err != nil {
		return "", "", fmt.Errorf("the object store path %q is not a URL: %w", raw, err)
	}
	if parsed.Scheme != "s3" {
		return "", "", fmt.Errorf("the object store path %q must use the s3 scheme, not %q",
			raw, parsed.Scheme)
	}
	if parsed.Host == "" {
		return "", "", fmt.Errorf("the object store path %q names no bucket", raw)
	}
	// pgBackRest wants an absolute repository path, and an empty prefix is the bucket root.
	prefix = "/" + strings.Trim(parsed.Path, "/")
	return parsed.Host, prefix, nil
}

// endpointSettings translates an endpoint URL into the host, port and addressing style
// pgBackRest wants.
//
// Path-style addressing is selected whenever an endpoint is given at all. Virtual-host
// style requires a wildcard DNS record per bucket, which S3-compatible stores run inside a
// cluster do not have, and getting this wrong produces a name resolution failure rather
// than anything that points at the cause.
func endpointSettings(endpoint string) []setting {
	endpoint = strings.TrimSpace(endpoint)
	if endpoint == "" {
		return nil
	}
	host := endpoint
	port := ""
	if parsed, err := url.Parse(endpoint); err == nil && parsed.Host != "" {
		host = parsed.Hostname()
		port = parsed.Port()
	}
	settings := []setting{
		{"repo1-s3-endpoint", host},
		{"repo1-s3-uri-style", "path"},
	}
	if port != "" {
		settings = append(settings, setting{"repo1-storage-port", port})
	}
	return settings
}

// regionOrDefault supplies a region for stores that have no concept of one. pgBackRest
// requires the setting and signs with it, and an S3-compatible store that ignores regions
// accepts any value, so the conventional placeholder is the safe choice.
func regionOrDefault(region string) string {
	if strings.TrimSpace(region) == "" {
		return "us-east-1"
	}
	return region
}

// retentionDays converts the operator's retention window into whole days, and refuses a WAL
// window shorter than the full-backup window.
//
// That combination is not merely suboptimal, it is unrestorable: expiring WAL before the
// oldest full backup leaves a base backup that cannot be replayed to consistency, which
// looks like a healthy repository right up until somebody tries to use it.
func retentionDays(repository Repository) (int, error) {
	full, err := ParseRetention(repository.RetentionFull)
	if err != nil {
		return 0, fmt.Errorf("retention.full: %w", err)
	}
	wal, err := ParseRetention(repository.RetentionWAL)
	if err != nil {
		return 0, fmt.Errorf("retention.wal: %w", err)
	}
	if wal < full {
		return 0, fmt.Errorf(
			"retention.wal (%s) is shorter than retention.full (%s), which expires the WAL "+
				"the oldest full backup needs to reach consistency",
			repository.RetentionWAL, repository.RetentionFull)
	}
	return full, nil
}

// ParseRetention reads a retention window written as a count and a unit: 30d, 4w, 6m.
//
// Months are 30 days. A retention window is a coarse operational promise, not a calendar
// calculation, and pgBackRest expresses it in days.
func ParseRetention(value string) (int, error) {
	value = strings.TrimSpace(value)
	if value == "" {
		return 0, fmt.Errorf("a retention window cannot be empty")
	}
	unit := value[len(value)-1]
	count, err := strconv.Atoi(value[:len(value)-1])
	if err != nil || count < 1 {
		return 0, fmt.Errorf("%q is not a positive count followed by d, w or m", value)
	}
	switch unit {
	case 'd':
		return count, nil
	case 'w':
		return count * 7, nil
	case 'm':
		return count * 30, nil
	default:
		return 0, fmt.Errorf("%q ends in %q; the units are d, w and m", value, string(unit))
	}
}
