---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pgelastic.io
  resources:
  - pgelasticclasses
  - pgelasticpools
  - pginstances
  - pgtenantmigrations
  - pgtenants
  - pgworkloadclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgelastic.io
  resources:
  - pgelasticclasses/finalizers
  - pgelasticpools/finalizers
  - pginstances/finalizers
  - pgtenantmigrations/finalizers
  - pgtenants/finalizers
  - pgworkloadclasses/finalizers
  verbs:
  - update
- apiGroups:
  - pgelastic.io
  resources:
  - pgelasticclasses/status
  - pgelasticpools/status
  - pginstances/status
  - pgtenantmigrations/status
  - pgtenants/status
  - pgworkloadclasses/status
  verbs:
  - get
  - patch
  - update
