---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pgelastic.io
  resources:
  - pgbackups
  - pgelasticclasses
  - pgelasticpools
  - pginstances
  - pgrestores
  - pgtenantmigrations
  - pgtenants
  - pgworkloadclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgelastic.io
  resources:
  - pgbackups/status
  - pgelasticclasses/status
  - pgelasticpools/status
  - pginstances/status
  - pgrestores/status
  - pgtenantmigrations/status
  - pgtenants/status
  - pgtenantusers/status
  - pgworkloadclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pgelastic.io
  resources:
  - pgelasticclasses/finalizers
  - pgelasticpools/finalizers
  - pginstances/finalizers
  - pgtenantmigrations/finalizers
  - pgtenants/finalizers
  - pgworkloadclasses/finalizers
  verbs:
  - update
- apiGroups:
  - pgelastic.io
  resources:
  - pgtenantusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
