apiVersion: pgelastic.io/v1alpha1
kind: PgInstance
metadata:
  labels:
    app.kubernetes.io/name: pgelastic
    app.kubernetes.io/managed-by: kustomize
  name: pginstance-sample
spec:
  # TODO(user): Add fields here
