/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package agent

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// What pgBackRest leaves in a restored data directory, verbatim.
const restoredAutoConf = `# Do not edit this file manually!
# It will be overwritten by the ALTER SYSTEM command.

# Recovery settings generated by pgBackRest restore on 2026-07-31 22:45:36
restore_command = '/agent/pgelastic-instance wal-restore --name %f --target %p'
recovery_target_time = '2026-07-31 22:45:27.721761+00'
recovery_target_action = 'promote'
`

// A recovery target belongs to the restore that produced the primary and to nothing else.
//
// PostgreSQL does not remove these on promotion, so they are still in postgresql.auto.conf
// when a standby clones, and pg_basebackup copies that file verbatim. The standby then enters
// recovery with a target older than the base backup it just took and refuses to start with
// "requested recovery stop point is before consistent recovery point" - and because
// synchronous_standby_names names those standbys, every commit on the restored primary then
// blocks for ever while the instance reports itself Ready.
func TestACloneDoesNotInheritTheRecoveryTarget(t *testing.T) {
	dataDir := t.TempDir()
	path := filepath.Join(dataDir, "postgresql.auto.conf")
	if err := os.WriteFile(path, []byte(restoredAutoConf), 0o600); err != nil {
		t.Fatalf("seeding: %v", err)
	}

	if err := discardRecoveryTarget(dataDir); err != nil {
		t.Fatalf("discarding: %v", err)
	}

	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading back: %v", err)
	}
	if strings.Contains(string(body), "recovery_target") {
		t.Errorf("a recovery target survived the clone:\n%s", body)
	}
	// restore_command is not a recovery target. A standby needs it to fetch a segment the
	// primary has already recycled, which is the case re-cloning exists to avoid.
	if !strings.Contains(string(body), "restore_command") {
		t.Errorf("restore_command was discarded along with the target:\n%s", body)
	}
}

// The ordinary case: an instance that was never restored has no such file until something
// writes one, and a member joining it must not fail because of that.
func TestDiscardingARecoveryTargetThatIsNotThere(t *testing.T) {
	if err := discardRecoveryTarget(t.TempDir()); err != nil {
		t.Fatalf("a data directory with no postgresql.auto.conf was an error: %v", err)
	}
}
